config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :tenant_accounts,
             :sign_out_via => [ :delete, :get ],
             controllers: {
                 omniauth_callbacks: 'omniauth_callbacks',
                 confirmations: 'confirmations'
             }

  get '/', to: 'cars#index'
  resources :cars

  put 'tenants/update', to: 'tenants#update'
  get 'resend_confirmation', to: 'tenants#resend_confirmation'
  get 'renters/reject_email', to: 'tenants#reject_email'

  post 'create_order', to: 'orders#create_order'
  get 'orders/accept', to: 'orders#accept'
  get 'orders/decline', to: 'orders#decline'

  get 'password_reset_form', to: 'tenant_accounts#password_reset_form'
  post 'password_reset', to: 'tenant_accounts#password_reset'
  get 'password_reset_successful', to: 'tenant_accounts#password_reset_successful'
  get 'password_reset_error', to: 'tenant_accounts#password_reset_error'

  #get 'tests/xml', to: 'tests#test_xml'
  #get 'tests/emails', to: 'tests#test_email_views'

  namespace :admin do
    root to: redirect('/admin/cars')

    resources :colors
    resources :engines
    resources :transmissions
    resources :bodies
    resources :cities
    resources :users
    resources :tenants, path: :renters
    resources :cars
    resources :mail_messages
    resources :orders
    resources :discounts
    resources :discount_types
    resources :tenant_accounts
    resources :acriss_codes
    resources :partner_offices
    resources :marks
    resources :samplers
    resources :currencies

    post 'partners/switch', to: 'partners#partners_switch_status'
    post 'tenants/merge', to: 'tenants#merge_tenants'
    get 'renters_merge_form', to: 'tenants#tenants_merge_form'

    namespace :datatables do
      resources :users,  only: %i[index]
      resources :tenants, path: :renters,  only: %i[index]
      resources :cars,   only: %i[index]
      resources :mail_messages, only: %i[index]
      resources :orders, only: %i[index]
      resources :discounts, only: %i[index]
      resources :discount_types, only: %i[index]
      resources :tenant_accounts, only: %i[index]
      resources :acriss_codes, only: %i[index]
      resources :partner_offices, only: %i[index]
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
    end

    post 'dictionaries/update', to: 'dictionaries#update'
    get 'dictionaries/load', to: 'dictionaries#load'

    post 'currencies/update_all_currencies', to: 'currencies#update_all_currencies'
    get 'rules_for_robots', to: 'utils#robots'
  end

  namespace :api do
    namespace :v1 do
      post 'wallet/pkpass', to: 'wallet#generate_pkpass'

      mount_devise_token_auth_for 'TenantAccount', at: 'auth', skip: [:omniauth_callbacks]

      resources :cars, only: %i[index show]
      resources :bodies, only: %i[index]
      resources :engines, only: %i[index]
      resources :transmissions, only: %i[index]
      resources :colors, only: %i[index]
      resources :cities, only: %i[index]
      resources :feedback, only: %i[create]
      post 'feedback/create_alt', to: 'feedback#create_alt'

      resources :orders, only: %i[create]
      post 'orders/pay', to: 'orders#pay'
      post 'orders/create_car_request', to: 'orders#create_car_request'
      post 'orders/create_partner_car_request', to: 'orders#create_partner_car_request'
      get 'orders/my', to: 'orders#my'
      resources :tenants, only: %i[] do
        collection do
          get  :me
          put  :me
          post :oauth
          post :auth
          
          get :my_cars
          post :create_car
          post :create_car_2
          put :update_car
          put :update_car_2
          delete :remove_car
        end
      end
      post 'tenants/resend_confirmation', to: 'tenants#resend_confirmation'
      post 'tenants/add_push_token', to: 'tenants#add_push_token'
      post 'tenants/update_password', to: 'tenants#update_password'
      post 'tenants/reset_password', to: 'tenants#reset_password'
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
      post 'load_file', to: 'resources#load_file'
    end
  end
end

app/models/sampler.rb
class Sampler < ApplicationRecord
  belongs_to :mark
end

app/controllers/admin/datatables/samplers_controller.rb
class Admin::Datatables::SamplersController < AdminController
  def index
    respond_to do |format|
      format.json { render json: SamplerDatatable.new(view_context) }
    end
  end
end

app/controllers/admin/samplers_controller.rb
class Admin::SamplersController < AdminController
  def index
    # stub
  end

  def new
    @sampler = Sampler.new
  end

  def edit
    @sampler = Sampler.find_by(id: params[:id])
  end

  def create
    @sampler = Sampler.new(sampler_params)
    redirect_to edit_admin_sampler_path(@sampler.id), notice: 'Модель автомобиля успешно создана.' if @sampler.save
  end

  def update
    @sampler = Sampler.find_by(id: params[:id])
    @sampler.update_attributes(sampler_params)
    redirect_to edit_admin_sampler_path(@sampler.id), notice: 'Модель автомобиля успешно обновлена.' if @sampler.errors.blank?
  end

  def destroy
    @sampler = Sampler.find_by(id: params[:id]).destroy
    redirect_to admin_samplers_path, notice: 'Модель автомобиля успешно удалена.'
  end

  private

  def sampler_params
    params.require(:sampler).permit!.except(:id)
  end
end

app/controllers/api/v1/samplers_controller.rb
class Api::V1::SamplersController < Api::V1::BaseController
  def index
    Api::V1::Sampler::Index::Interactor.new.call(sampler_params) do |m|
      m.success do |response|
        @samplers = response
      end

      m.failure do |response|
        render json: { status: :error, errors: response }, status: :bad_request
      end
    end
  end

  private

  def sampler_params
    params_ = params.permit!
    params_['app'] = request.headers['app']
    params_
  end
end

app/views/admin/samplers/_form.html.erb
<div class="be-content">
  <div class="main-content container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= @sampler.id ? 'Редактирование модели автомобилей' : 'Создание новой модели автомобилей' %>
            <div class="tools">
              <%= link_to '<span class="icon mdi mdi-long-arrow-return"></span>'.html_safe, admin_samplers_path %>
            </div>
          </div>

          <div class="panel-body">
            <%= bootstrap_form_for @sampler, url: {action: @sampler.id ? 'update' : 'create'}, html: {class: 'form-horizontal form-bordered col-md-12 col-sm-12 col-xs-12 p0'},
                                   layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-10' do |f| %>


              <%= f.collection_select :mark_id, Mark.all, :id, :name, class: 'form-control', include_blank: true, label: 'Марка автомобиля' %>
              <%= f.text_field :name, label: 'Модель автомобиля' %>

              <hr/>
              <p class="text-right">
                <button type="submit" class="btn btn-space btn-primary">Сохранить</button>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/samplers/create.html.erb
<%== render 'form' %>

app/views/admin/samplers/edit.html.erb
<%== render 'form' %>

app/views/admin/samplers/index.html.erb
<div class="be-content">
  <div class="main-content container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default panel-table">
          <div class="panel-heading">
            Модели автомобилей
            <div class="tools">
              <%= link_to '<span class="icon mdi mdi-long-arrow-return"></span>'.html_safe, 'dictionaries/load' %>
              <%= link_to '<span class="icon mdi mdi-plus"></span>'.html_safe, new_admin_sampler_path %>
            </div>
          </div>
          <div class="panel-body">
            <table class="table" id="samplers_table" data-source="<%= admin_datatables_samplers_path(format: :json) %>">
              <thead>
              <tr>
                <th style="width: 10%">ID</th>
                <th>ID марки</th>
                <th>Название модели</th>
                <th>Управление</th>
              </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/samplers/new.html.erb
<%== render 'form' %>

app/views/admin/samplers/update.html.erb
<%== render 'form' %>