config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :tenant_accounts,
             :sign_out_via => [ :delete, :get ],
             controllers: {
                 omniauth_callbacks: 'omniauth_callbacks',
                 confirmations: 'confirmations'
             }

  get '/', to: 'cars#index'
  resources :cars

  put 'tenants/update', to: 'tenants#update'
  get 'resend_confirmation', to: 'tenants#resend_confirmation'
  get 'renters/reject_email', to: 'tenants#reject_email'

  post 'create_order', to: 'orders#create_order'
  get 'orders/accept', to: 'orders#accept'
  get 'orders/decline', to: 'orders#decline'

  get 'password_reset_form', to: 'tenant_accounts#password_reset_form'
  post 'password_reset', to: 'tenant_accounts#password_reset'
  get 'password_reset_successful', to: 'tenant_accounts#password_reset_successful'
  get 'password_reset_error', to: 'tenant_accounts#password_reset_error'

  #get 'tests/xml', to: 'tests#test_xml'
  #get 'tests/emails', to: 'tests#test_email_views'

  namespace :admin do
    root to: redirect('/admin/cars')

    resources :colors
    resources :engines
    resources :transmissions
    resources :bodies
    resources :cities
    resources :users
    resources :tenants, path: :renters
    resources :cars
    resources :mail_messages
    resources :orders
    resources :discounts
    resources :discount_types
    resources :tenant_accounts
    resources :acriss_codes
    resources :partner_offices
    resources :marks
    resources :samplers
    resources :currencies

    post 'partners/switch', to: 'partners#partners_switch_status'
    post 'tenants/merge', to: 'tenants#merge_tenants'
    get 'renters_merge_form', to: 'tenants#tenants_merge_form'

    namespace :datatables do
      resources :users,  only: %i[index]
      resources :tenants, path: :renters,  only: %i[index]
      resources :cars,   only: %i[index]
      resources :mail_messages, only: %i[index]
      resources :orders, only: %i[index]
      resources :discounts, only: %i[index]
      resources :discount_types, only: %i[index]
      resources :tenant_accounts, only: %i[index]
      resources :acriss_codes, only: %i[index]
      resources :partner_offices, only: %i[index]
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
    end

    post 'dictionaries/update', to: 'dictionaries#update'
    get 'dictionaries/load', to: 'dictionaries#load'

    post 'currencies/update_all_currencies', to: 'currencies#update_all_currencies'
    get 'rules_for_robots', to: 'utils#robots'
  end

  namespace :api do
    namespace :v1 do
      post 'wallet/pkpass', to: 'wallet#generate_pkpass'

      mount_devise_token_auth_for 'TenantAccount', at: 'auth', skip: [:omniauth_callbacks]

      resources :cars, only: %i[index show]
      resources :bodies, only: %i[index]
      resources :engines, only: %i[index]
      resources :transmissions, only: %i[index]
      resources :colors, only: %i[index]
      resources :cities, only: %i[index]
      resources :feedback, only: %i[create]
      post 'feedback/create_alt', to: 'feedback#create_alt'

      resources :orders, only: %i[create]
      post 'orders/pay', to: 'orders#pay'
      post 'orders/create_car_request', to: 'orders#create_car_request'
      post 'orders/create_partner_car_request', to: 'orders#create_partner_car_request'
      get 'orders/my', to: 'orders#my'
      resources :tenants, only: %i[] do
        collection do
          get  :me
          put  :me
          post :oauth
          post :auth
          
          get :my_cars
          post :create_car
          post :create_car_2
          put :update_car
          put :update_car_2
          delete :remove_car
        end
      end
      post 'tenants/resend_confirmation', to: 'tenants#resend_confirmation'
      post 'tenants/add_push_token', to: 'tenants#add_push_token'
      post 'tenants/update_password', to: 'tenants#update_password'
      post 'tenants/reset_password', to: 'tenants#reset_password'
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
      post 'load_file', to: 'resources#load_file'
    end
  end
end

app/views/admin/partials/_flash.html.erb
<% if flash.present? %>
    <% flash.each do |name, msg| %>
        <% klass = name == 'alert' ? 'alert-danger' : 'alert-success' %>
        <% icon  = name == 'alert' ? 'mdi-close-circle-o' : 'mdi-check' %>

        <div class="be-content flash-header">
          <div class="main-content container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <div role="alert" class="alert <%= klass %> alert-icon alert-icon-colored alert-dismissible">
                  <div class="icon"><span class="mdi <%= icon %>"></span></div>
                  <div class="message">
                    <button id="flashCloseBtn" type="button" data-dismiss="alert" aria-label="Close" class="close">
                      <span aria-hidden="true" class="mdi mdi-close"></span>
                    </button>
                    <%= msg %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/admin/partials/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top be-top-header">
  <div class="container-fluid">
    <div class="navbar-header"><a href="/admin" class="navbar-brand"></a></div>
    <div class="be-right-navbar">
      <ul class="nav navbar-nav navbar-right be-user-nav">
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
            <img src="<%= asset_path 'admin/avatar.png' %>" alt="Avatar">
          </a>
          <ul role="menu" class="dropdown-menu">
            <li>
              <div class="user-info">
                <div class="user-name">Администратор</div>
              </div>
            </li>
            <li>
              <%= link_to '<span class="icon mdi mdi-power"></span> Выйти'.html_safe,
                          destroy_admin_session_path(authenticity_token: form_authenticity_token),
                          method: :delete,
                          title: 'Выйти' %>
            </li>
          </ul>
        </li>
      </ul>
      <div class="page-title"><span>Административная панель</span></div>
    </div>
  </div>
</nav>

app/views/admin/partials/_left_sidebar.html.erb
<div class="be-left-sidebar">
  <div class="left-sidebar-wrapper">
    <div class="left-sidebar-spacer">
      <div class="left-sidebar-scroll">
        <div class="left-sidebar-content">
          <ul class="sidebar-elements">
            <li>
              <!--<a href="<%= admin_users_path %>"><i class="icon mdi mdi-accounts-list"></i><span>Автовладельцы</span></a>-->
              <a href="<%= admin_tenants_path %>"><i class="icon mdi mdi-accounts-list"></i><span>Пользователи</span></a>
              <!--<a href="<%= admin_tenant_accounts_path %>"><i class="icon mdi mdi-accounts-list"></i><span>Аккаунты пользователей</span></a>-->
              <a href="<%= admin_mail_messages_path %>"><i class="icon mdi mdi-accounts-list"></i><span>Письма</span></a>
              <a href="<%= admin_rules_for_robots_path %>"><i class="icon mdi mdi-accounts-list"></i><span>Файл robots.txt</span></a>
            </li>
            <li class="divider">Автомобили</li>
            <li>
              <a href="<%= admin_cars_path %>"><i class="icon mdi mdi-car"></i><span>Автомобили</span></a>
              <a href="<%= admin_bodies_path %>"><i class="icon mdi mdi-car-wash"></i><span>Типы кузовов</span></a>
              <a href="<%= admin_engines_path %>"><i class="icon mdi mdi-widgets"></i><span>Типы двигателей</span></a>
              <a href="<%= admin_transmissions_path %>"><i class="icon mdi mdi-settings"></i><span>Коробки передач</span></a>
              <a href="<%= admin_colors_path %>"><i class="icon mdi mdi-invert-colors"></i><span>Цвета</span></a>
              <a href="<%= admin_cities_path %>"><i class="icon mdi mdi-city"></i><span>Города</span></a>
              <!--<a href="<%= admin_partner_offices_path %>"><i class="icon mdi mdi-city"></i><span>Партнерские офисы</span></a>-->
              <!--<a href="<%= admin_acriss_codes_path %>"><i class="icon mdi mdi-car"></i><span>ACRISS Коды</span></a>-->
              <a href="<%= admin_marks_path %>"><i class="icon mdi mdi-car"></i><span>Марки автомобилей</span></a>
              <a href="<%= admin_samplers_path %>"><i class="icon mdi mdi-car"></i><span>Модели автомобилей</span></a>
            </li>
            <li class="divider">Заказы</li>
            <li>
              <a href="<%= admin_orders_path %>"><i class="icon mdi mdi-car"></i><span>Заказы</span></a>
              <a href="<%= admin_discounts_path %>"><i class="icon mdi mdi-car"></i><span>Скидки</span></a>
              <a href="<%= admin_discount_types_path %>"><i class="icon mdi mdi-car"></i><span>Типы скидок</span></a>
            </li>
            <li class="divider">Прочее</li>
            <li>
              <a href="<%= admin_currencies_path %>"><i class="icon mdi mdi-settings"></i><span>Курсы валют</span></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>