config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :tenant_accounts,
             :sign_out_via => [ :delete, :get ],
             controllers: {
                 omniauth_callbacks: 'omniauth_callbacks',
                 confirmations: 'confirmations'
             }

  get '/', to: 'cars#index'
  resources :cars

  put 'tenants/update', to: 'tenants#update'
  get 'resend_confirmation', to: 'tenants#resend_confirmation'
  get 'renters/reject_email', to: 'tenants#reject_email'

  post 'create_order', to: 'orders#create_order'
  get 'orders/accept', to: 'orders#accept'
  get 'orders/decline', to: 'orders#decline'

  get 'password_reset_form', to: 'tenant_accounts#password_reset_form'
  post 'password_reset', to: 'tenant_accounts#password_reset'
  get 'password_reset_successful', to: 'tenant_accounts#password_reset_successful'
  get 'password_reset_error', to: 'tenant_accounts#password_reset_error'

  #get 'tests/xml', to: 'tests#test_xml'
  #get 'tests/emails', to: 'tests#test_email_views'

  namespace :admin do
    root to: redirect('/admin/cars')

    resources :colors
    resources :engines
    resources :transmissions
    resources :bodies
    resources :cities
    resources :users
    resources :tenants, path: :renters
    resources :cars
    resources :mail_messages
    resources :orders
    resources :discounts
    resources :discount_types
    resources :tenant_accounts
    resources :acriss_codes
    resources :partner_offices
    resources :marks
    resources :samplers
    resources :currencies

    post 'partners/switch', to: 'partners#partners_switch_status'
    post 'tenants/merge', to: 'tenants#merge_tenants'
    get 'renters_merge_form', to: 'tenants#tenants_merge_form'

    namespace :datatables do
      resources :users,  only: %i[index]
      resources :tenants, path: :renters,  only: %i[index]
      resources :cars,   only: %i[index]
      resources :mail_messages, only: %i[index]
      resources :orders, only: %i[index]
      resources :discounts, only: %i[index]
      resources :discount_types, only: %i[index]
      resources :tenant_accounts, only: %i[index]
      resources :acriss_codes, only: %i[index]
      resources :partner_offices, only: %i[index]
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
    end

    post 'dictionaries/update', to: 'dictionaries#update'
    get 'dictionaries/load', to: 'dictionaries#load'

    post 'currencies/update_all_currencies', to: 'currencies#update_all_currencies'
    get 'rules_for_robots', to: 'utils#robots'
  end

  namespace :api do
    namespace :v1 do
      post 'wallet/pkpass', to: 'wallet#generate_pkpass'

      mount_devise_token_auth_for 'TenantAccount', at: 'auth', skip: [:omniauth_callbacks]

      resources :cars, only: %i[index show]
      resources :bodies, only: %i[index]
      resources :engines, only: %i[index]
      resources :transmissions, only: %i[index]
      resources :colors, only: %i[index]
      resources :cities, only: %i[index]
      resources :feedback, only: %i[create]
      post 'feedback/create_alt', to: 'feedback#create_alt'

      resources :orders, only: %i[create]
      post 'orders/pay', to: 'orders#pay'
      post 'orders/create_car_request', to: 'orders#create_car_request'
      post 'orders/create_partner_car_request', to: 'orders#create_partner_car_request'
      get 'orders/my', to: 'orders#my'
      resources :tenants, only: %i[] do
        collection do
          get  :me
          put  :me
          post :oauth
          post :auth
          
          get :my_cars
          post :create_car
          post :create_car_2
          put :update_car
          put :update_car_2
          delete :remove_car
        end
      end
      post 'tenants/resend_confirmation', to: 'tenants#resend_confirmation'
      post 'tenants/add_push_token', to: 'tenants#add_push_token'
      post 'tenants/update_password', to: 'tenants#update_password'
      post 'tenants/reset_password', to: 'tenants#reset_password'
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
      post 'load_file', to: 'resources#load_file'
    end
  end
end

app/models/acriss_code.rb
class AcrissCode < ApplicationRecord
    mount_uploader :image, CarImageUploader
end

app/controllers/admin/acriss_codes_controller.rb
class Admin::AcrissCodesController < AdminController
  def index
    # stub
  end

  def new
    @acriss = AcrissCode.new
  end

  def edit
    @acriss = AcrissCode.find_by(id: params[:id])
  end

  def create
    @acriss = AcrissCode.new(_params)
    redirect_to edit_admin_acriss_code_path(@acriss.id), notice: 'Код успешно создан.' if @acriss.save
  end

  def update
    @acriss = AcrissCode.find_by(id: params[:id])
    @acriss.update_attributes(_params)
    redirect_to edit_admin_acriss_code_path(@acriss.id), notice: 'Код успешно обновлен.' if @acriss.errors.blank?
  end

  def destroy
    @acriss = AcrissCode.find_by(id: params[:id]).destroy
    redirect_to admin_acriss_codes_path, notice: 'Код успешно удален.'
  end

  private

  def _params
    params.require(:acriss_code).permit!.except(:id)
  end
end

app/controllers/admin/datatables/acriss_codes_controller.rb
class Admin::Datatables::AcrissCodesController < AdminController
  def index
    respond_to do |format|
      format.json { render json: AcrissCodeDatatable.new(view_context) }
    end
  end
end

app/views/admin/acriss_codes/_form.html.erb
<div class="be-content">
  <div class="main-content container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= @acriss.id ? 'Редактирование ACRISS Кода' : 'Создание нового ACRISS Кода' %>
            <div class="tools">
              <%= link_to '<span class="icon mdi mdi-long-arrow-return"></span>'.html_safe, admin_acriss_codes_path %>
            </div>
          </div>

          <div class="panel-body">
            <%= bootstrap_form_for @acriss, url: {action: @acriss.id ? 'update' : 'create'},
                                   html: {class: 'form-horizontal form-bordered col-md-12 col-sm-12 col-xs-12 p0'},
                                   layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-10' do |f| %>

              <div class="form-group avatar-wrapper">
                <label class="control-label col-md-2">Фотография</label>
                <div class="col-md-10">
                  <% image_link = @acriss.image? ? @acriss.image_url : asset_path('admin/200_hold.png') %>
                  <%= image_tag(image_link, class: 'preview-image-container') %>
                  <%= f.file_field :image, label: 'Фотография' %>
                  <% if @acriss.image? %>
                    <label>
                      <%= f.check_box :remove_image, label: 'Удалить изображение' %>
                    </label>
                  <% end %>
                </div>
              </div>

              <%= f.text_field :acriss_code, label: 'Acriss Code' %>
              <%= f.text_field :group, label: 'Group' %>
              <%= f.text_field :type_of_car, label: 'Type of car' %>
              <%= f.text_field :year_of_production, label: 'Year of production' %>
              <%= f.number_field :seats, label: 'Seats' %>
              <%= f.number_field :doors, label: 'Doors' %>
              <%= f.check_box :air_condition, label: 'Air Condition' %>
              <%= f.number_field :deposit, label: 'Deposit' %>
              <%= f.text_field :guaranteed, label: 'Guaranteed' %>
              <%= f.number_field :deposit_eur, label: 'Deposit EUR' %>
              <%= f.number_field :cross_border_fee, label: 'Cross border fee' %>

              <p class="text-right">
                <button type="submit" class="btn btn-space btn-primary">Сохранить</button>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/acriss_codes/create.html.erb
<%== render 'form' %>

app/views/admin/acriss_codes/edit.html.erb
<%== render 'form' %>

app/views/admin/acriss_codes/index.html.erb
<div class="be-content">
  <div class="main-content container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default panel-table">
          <div class="panel-heading">
            ACRISS Коды
            <div class="tools">
              <%= link_to '<span class="icon mdi mdi-plus"></span>'.html_safe, new_admin_acriss_code_path %> 
            </div>
          </div>
          <div class="panel-body" style="overflow: auto;">
            <table class="table" id="acriss_codes_table" data-source="<%= admin_datatables_acriss_codes_path(format: :json) %>">
              <thead>
              <tr>
                <th>ID</th>
                <th>Код</th>
                <th>Группа</th>
                <th>Типы автомобилей</th>
                <th>Управление</th>
              </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/acriss_codes/new.html.erb
<%== render 'form' %>

app/views/admin/acriss_codes/update.html.erb
<%== render 'form' %>