config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :tenant_accounts,
             :sign_out_via => [ :delete, :get ],
             controllers: {
                 omniauth_callbacks: 'omniauth_callbacks',
                 confirmations: 'confirmations'
             }

  get '/', to: 'cars#index'
  resources :cars

  put 'tenants/update', to: 'tenants#update'
  get 'resend_confirmation', to: 'tenants#resend_confirmation'
  get 'renters/reject_email', to: 'tenants#reject_email'

  post 'create_order', to: 'orders#create_order'
  get 'orders/accept', to: 'orders#accept'
  get 'orders/decline', to: 'orders#decline'

  get 'password_reset_form', to: 'tenant_accounts#password_reset_form'
  post 'password_reset', to: 'tenant_accounts#password_reset'
  get 'password_reset_successful', to: 'tenant_accounts#password_reset_successful'
  get 'password_reset_error', to: 'tenant_accounts#password_reset_error'

  #get 'tests/xml', to: 'tests#test_xml'
  #get 'tests/emails', to: 'tests#test_email_views'

  namespace :admin do
    root to: redirect('/admin/cars')

    resources :colors
    resources :engines
    resources :transmissions
    resources :bodies
    resources :cities
    resources :users
    resources :tenants, path: :renters
    resources :cars
    resources :mail_messages
    resources :orders
    resources :discounts
    resources :discount_types
    resources :tenant_accounts
    resources :acriss_codes
    resources :partner_offices
    resources :marks
    resources :samplers
    resources :currencies

    post 'partners/switch', to: 'partners#partners_switch_status'
    post 'tenants/merge', to: 'tenants#merge_tenants'
    get 'renters_merge_form', to: 'tenants#tenants_merge_form'

    namespace :datatables do
      resources :users,  only: %i[index]
      resources :tenants, path: :renters,  only: %i[index]
      resources :cars,   only: %i[index]
      resources :mail_messages, only: %i[index]
      resources :orders, only: %i[index]
      resources :discounts, only: %i[index]
      resources :discount_types, only: %i[index]
      resources :tenant_accounts, only: %i[index]
      resources :acriss_codes, only: %i[index]
      resources :partner_offices, only: %i[index]
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
    end

    post 'dictionaries/update', to: 'dictionaries#update'
    get 'dictionaries/load', to: 'dictionaries#load'

    post 'currencies/update_all_currencies', to: 'currencies#update_all_currencies'
    get 'rules_for_robots', to: 'utils#robots'
  end

  namespace :api do
    namespace :v1 do
      post 'wallet/pkpass', to: 'wallet#generate_pkpass'

      mount_devise_token_auth_for 'TenantAccount', at: 'auth', skip: [:omniauth_callbacks]

      resources :cars, only: %i[index show]
      resources :bodies, only: %i[index]
      resources :engines, only: %i[index]
      resources :transmissions, only: %i[index]
      resources :colors, only: %i[index]
      resources :cities, only: %i[index]
      resources :feedback, only: %i[create]
      post 'feedback/create_alt', to: 'feedback#create_alt'

      resources :orders, only: %i[create]
      post 'orders/pay', to: 'orders#pay'
      post 'orders/create_car_request', to: 'orders#create_car_request'
      post 'orders/create_partner_car_request', to: 'orders#create_partner_car_request'
      get 'orders/my', to: 'orders#my'
      resources :tenants, only: %i[] do
        collection do
          get  :me
          put  :me
          post :oauth
          post :auth
          
          get :my_cars
          post :create_car
          post :create_car_2
          put :update_car
          put :update_car_2
          delete :remove_car
        end
      end
      post 'tenants/resend_confirmation', to: 'tenants#resend_confirmation'
      post 'tenants/add_push_token', to: 'tenants#add_push_token'
      post 'tenants/update_password', to: 'tenants#update_password'
      post 'tenants/reset_password', to: 'tenants#reset_password'
      resources :marks, only: %i[index]
      resources :samplers, only: %i[index]
      post 'load_file', to: 'resources#load_file'
    end
  end
end

app/models/car.rb
class Car < ApplicationRecord
  validates :mark_name, presence: true
  validates :sampler_name, presence: true
  #validates :address, presence: true
  validates :engine_id, presence: true, numericality: true
  validates :transmission_id, presence: true, numericality: true
  validates :city_id, presence: true, numericality: true
  validates :tenant_id, presence: true, numericality: true
  validates :production_year, presence: true, numericality: true
  validates :price_rub, presence: true, numericality: true

  belongs_to :color, optional: true
  belongs_to :engine
  belongs_to :transmission
  belongs_to :body
  belongs_to :city
  belongs_to :tenant

  before_save :resolve_full_name
  after_save :resolve_dynamic_link

  geocoded_by :address, lookup: :yandex
  after_validation :geocode, if: -> (obj) { obj.latitude.blank? && obj.longitude.blank? }

  # deprecated
  mount_uploader :image, CarImageUploader
  mount_uploaders :insurance_images, CarSupportImagesUploader
  mount_uploaders :contract_images, CarSupportImagesUploader

  def first_image
    imgs = images
    if imgs.empty?
      return nil
    end

    first_image = imgs.first
    unless first_image.present?
      return nil
    end
    
    return first_image
  end

  def images
    images_by_field("images_ids")
  end

  def contracts
    images_by_field("contract_images_ids") 
  end

  def get_insurances
    result = []

    raw_insurances = self.insurances
    unless raw_insurances.present?
      return result
    end

    unless raw_insurances.kind_of?(Array)
      return []
    end


    raw_insurances.each do |insurance|
      images = []

      images_ids = insurance["images_ids"]
      if images_ids.present? && images_ids.kind_of?(Array)
        images_ids.each do |id|
          res = ::Resource.find_by(id: id)
          if res.present?
            img = {
              id: res.id,
              url: Rails.application.secrets.full_host + res&.file&.url(:medium),
              original: Rails.application.secrets.full_host + res&.file&.url,
              medium: Rails.application.secrets.full_host + res&.file&.url(:medium)
            }
            images << img
          end 
        end
      end

      insurance_item = {
        name: insurance["name"],
        images: images
      }  
      result << insurance_item
    end

    return result
  end

  def friendly_price(currency = 'rub')
    price_origin = send("price_#{currency}")
    price = price_origin * 100
    if price % 100 == 0
      return price_origin.to_i
    else
      return price_origin
    end
  end

  def price_by_dates(date_from, date_to, currency = 'rub')
    days_count = (Date.parse(date_to.to_s) - Date.parse(date_from.to_s)).to_i

    if days_count >= 30
      return days_count * send("price_month_#{currency}")
    end

    if days_count >= 7
      return days_count * send("price_week_#{currency}")
    end

    if days_count >= 2
      return days_count * send("price_few_days_#{currency}")
    end

    days_count * send("price_#{currency}")
  end

  def daily_price_by_dates(date_from, date_to, currency = 'rub')
    days_count = (Date.parse(date_to.to_s) - Date.parse(date_from.to_s)).to_i

    if days_count >= 30
      return send("price_month_#{currency}")
    end

    if days_count >= 7
      return send("price_week_#{currency}")
    end

    if days_count >= 2
      return send("price_few_days_#{currency}")
    end

    send("price_#{currency}")
  end

  def convert_price(price, origin_currency, target_currency)
    origin_currency = origin_currency.upcase
    target_currency = target_currency.upcase

    price_rub = rub_from(price, origin_currency)
    target_price = rub_to(price_rub, target_currency)
    return target_price
  end

  private

  def resolve_full_name
    self.full_name = "#{mark_name} #{sampler_name}"
  end

  def resolve_dynamic_link
    if (not self.dynamic_link.present?) || (self.dynamic_link.empty?)
      car_id = self.id
      dynamic_link = build_dynamic_link(car_id)
      self.dynamic_link = dynamic_link
      self.save
    end
  end

  def build_dynamic_link(car_id)
    api_key = Rails.application.secrets.dynamic_link_api_key
    base_uri = 'https://firebasedynamiclinks.googleapis.com/v1/shortLinks?key=' + api_key

    require 'httparty'
    require 'json'

    body = {
        dynamicLinkInfo: {
            dynamicLinkDomain: "es5zs.app.goo.gl",
            link: Rails.application.secrets.full_host + "/cars/" + car_id.to_s + "/?id=" + car_id.to_s,
            androidInfo: {
                androidPackageName: "com.www.darenta",
                androidFallbackLink: "https://play.google.com/store/apps/details?id=com.www.darenta",
                androidMinPackageVersionCode: "0"
            },
            iosInfo: {
                iosBundleId: "ru.darenta.main",
                iosFallbackLink: "https://itunes.apple.com/app/apple-store/id963427615",
                iosCustomScheme: "",
                iosIpadFallbackLink: "",
                iosIpadBundleId: "",
                iosAppStoreId: "963427615"
            },
            navigationInfo: {
                enableForcedRedirect: false
            },
            socialMetaTagInfo: {
                socialTitle: "Darenta",
                socialDescription: "Аренда автомобилей от частных лиц",
                socialImageLink: ""
            }
        },
        suffix: {
            option: "SHORT"
        }
    }

    response = HTTParty.post(base_uri, :headers => {'Content-Type'=>'application/json'}, :body => body.to_json).body
    response_hash = JSON.parse(response).to_h
    dynamic_link = response_hash["shortLink"]
    if dynamic_link.present?
      return dynamic_link
    else
      return 'empty'
    end
  end

  def images_by_field(field_name)
    result = []

    #puts("field", self."#{ field_name }")
    raw_ids = send("#{field_name}")
    unless raw_ids.present?
      return []
    end

    unless raw_ids.kind_of?(Array)
      return []
    end

    raw_ids.each do |id|
      res = ::Resource.find_by(id: id)
      if res.present?
        img = {
          id: res.id,
          url: Rails.application.secrets.full_host + res&.file&.url(:medium),
          original: Rails.application.secrets.full_host + res&.file&.url,
          medium: Rails.application.secrets.full_host + res&.file&.url(:medium)
        }

        result << img
      end
    end

    return result
  end

  def rub_from(value, currency_code)
    ::Currency.new.rub_from(value, currency_code)
  end

  def rub_to(value, currency_code)
    ::Currency.new.rub_to(value, currency_code)
  end
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < AdminController
  def index
    # stub
  end

  # Открывает страницу создания нового автомобиля
  def new
    @car = Car.new
  end

  # Открывает страницу редактирования автомобиля
  def edit
    @car = Car.find_by(id: params[:id])
  end

  # Создает новый автомобиль в базе
  def create
    @car = Car.new(car_params)
    redirect_to edit_admin_car_path(@car.id), notice: 'Автомобиль успешно создан.' if @car.save
  end

  # Обновляет автомобиль в базе
  def update
    @car = Car.find_by(id: params[:id])
    if(!@car.changed?)
      @car.updated_at = DateTime.now
    end
    @car.update_attributes(car_params)

    if @car.is_notifications_enabled
      need_notify = params[:need_notify]
      if need_notify.present? && @car.is_moderated
        form = {
            car: @car,
            source: 'site'
        }
        
        TenantsCarModerationAcceptedJob.perform_later(form)
      end
    end

    redirect_to edit_admin_car_path(@car.id), notice: 'Автомобиль успешно обновлен.' if @car.errors.blank?
  end

  # Удаляет автомобиль из базы
  def destroy
    @car = Car.find_by(id: params[:id]).destroy
    redirect_to admin_cars_path, notice: 'Автомобиль успешно удален.'
  end

  private

  # Возвращает все передаваемые параметры, кроме id
  def car_params
    params.require(:car).permit!.except(:id)
  end
end

app/controllers/admin/datatables/cars_controller.rb
class Admin::Datatables::CarsController < AdminController
  def index
    respond_to do |format|
      format.json { render json: CarDatatable.new(view_context) }
    end
  end
end

app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < Api::V1::BaseController
  def index
    Api::V1::Car::Index::Interactor.new.call(car_params) do |m|
      m.success do |response|
        @cars = response[:our_cars]
        @partner_cars = response[:partner_cars]
      end

      m.failure do |response|
        render json: { status: :error, errors: response }, status: :bad_request
      end
    end
  end

  def show
    Api::V1::Car::Show::Interactor.new.call(car_params) do |m|
      m.success do |response|
        @car = response
      end

      m.failure do |response|
        render json: { status: :error, errors: response }, status: :bad_request
      end
    end
  end

  private

  def car_params
    params_ = params.permit!
    params_['app'] = request.headers['app']
    params_
  end
end

app/controllers/cars_controller.rb
class CarsController < SiteController
  skip_before_action :authenticate_tenant_account!, :only => [:index, :show]

  def index
    @cars = Car.where(is_moderated: true)
  end

  def new
    @car = Car.new
  end

  def show
    @car = Car.find_by(id: params[:id])
  end

  def edit
    # stub
  end

  def create
    # stub
  end

  def update
    # stub
  end

  def destroy
    # stub
  end
end

app/views/cars/index.html.erb
<% if current_tenant_account.present? %>
  <% current_tenant = Tenant.find_by(id: current_tenant_account.tenant_id) %>
  <% facebook_account = TenantAccount.find_by(tenant_id: current_tenant.id, provider: :facebook) %>
  <% google_account = TenantAccount.find_by(tenant_id: current_tenant.id, provider: :google) %>
  <% email_account = TenantAccount.find_by(tenant_id: current_tenant.id, provider: :email) %>
<% end %>
<%= render "tenants/personal" %>

<main id="panel">
  <header class="main">

    <button id="menu-toggle">
    </button>

    <div class="container">
      <div class="row top-line">
        <div class="logo">
          <img src="<%= asset_path 'pages/logo.png' %>"/>
        </div>
        <div class="logo-sign">
          Personal transport in your smartphone<br>
          <span class="logo-sign__sub">Cars around you, ready to go. Book for a few hours or a few days!</span>
        </div>
        <div class="social">
          <% unless tenant_account_signed_in? %>
            <div class="social__text">Log In</div>
            <%=  link_to "", tenant_account_facebook_omniauth_authorize_path, :class => "social__item fb"  %>
            <%=  link_to "", tenant_account_google_omniauth_authorize_path, :class => "social__item ggl"  %>
          <% end %>
        </div>
      </div>
      <div class="service-info">
        <div class="service-info__text">
          Darenta - online service that<br/>
          helps individuals to share insured cars<br/>
          with tourists and other renters
        </div>
        <div class="service-info__sign">
          The service is available on Android and iOS mobile devices
        </div>
      </div>
      <div class="stores">
        <a href="https://play.google.com/store/apps/details?id=com.www.darenta" class="stores__item play-market" target="_blank"></a>
        <a href="https://itunes.apple.com/ru/app/id1441007004" class="stores__item app-store" target="_blank"></a>
      </div>
    </div>

  </header>

  <section class="content">
    <div class="container">
      <div class="car-offers">

        <% @cars.each do |car| %>
          <% if car.price_rub.present? %>
            <div class="car-offers__item row">
              <div class="car-offers__item-pic">
                <% if car.images.length != 0 %>
                  <img src="<%= car.first_image[:original] %>" alt="">
                <% else %>
                  <img src="<%= asset_path 'temp/mazda.png' %>" alt="">
                <% end %>
              </div>
              <div class="car-offers__item-content">
                <div class="car-name">
                  <%= car.full_name %>
                </div>
                <ul class="car-props">
                  <li class="car-props__item price">
                    <%= car.friendly_price('usd') %> usd per a day
                  </li>
                  <li class="car-props__item location">
                    <%= City.find_by(id: car.city_id).name_en&.strip %>
                  </li>
                  <li class="car-props__item helm">
                    <%= Transmission.find_by(id: car.transmission_id).name_en&.strip %>
                  </li>
                </ul>
              </div>
              <div class="car-offers__item-person">
                <% tenant = Tenant.find_by(id: car.tenant_id) %>
                <div class="person-photo">
                  <img src="<%= tenant.avatar %>" alt="" />
                </div>
                <div class="person-name">
                  <% name = tenant.t_first_name_en.present? ? tenant.t_first_name_en : tenant.t_first_name_ru %>
                  <%= name %>
                </div>
                <%= button_to "Rent for #{car.friendly_price('usd')} usd", car_path(car.id), remote: true, method: :get, :class => "btn btn-rent" %>
              </div>
            </div>
          <% end %>
        <% end %>

      </div>
    </div>
  </section>
</main>

<%= javascript_include_tag "pages/main.js", "data-turbolinks-track" => true %>